/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Flujos;
import Business.Principal;
import static Business.Principal.Actualizar;
import static Business.Principal.BDControlador;
import static Business.Principal.BDEstudiante;
import Data.Controlador;
import Data.Externo;
import Data.Usuario;
import static UI.Panel_Deuda.externoactual;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LG Z360
 */
public class Deuda extends javax.swing.JPanel {

    /**
     * Creates new form Deuda
     */
    public Deuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tDeuda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(290, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 109, 81));
        jLabel2.setText("Deuda");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tDeuda.setForeground(new java.awt.Color(0, 109, 81));
        tDeuda.setText("jLabel3");
        add(tDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 109, 81));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, -5, 90, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(tDeuda.getText()=="0"){
          JFrame parentFrame = new JFrame();
        JOptionPane.showMessageDialog(parentFrame, "No hay deuda ha cancelar");  
        }
        Controlador c = (Controlador)Inicio.usuarioActual;
        c.acumularDeuda(Panel_Deuda.externoactual.getDeuda());
        for(Controlador e: Principal.BDControlador){
            if(e.getNombre().equals(Panel_Deuda.externoactual.getNombre())){
               e.setAcumulodeuda(c.getAcumulodeuda());
            }
        }
        Flujos.Guardar(BDControlador,  "Controlador");
        Actualizar(BDControlador,"Controlador");
        Inicio.usuarioActual=(Usuario)c;
                        
        Panel_Deuda.externoactual.setDeuda(0);
        for(Externo e: Principal.BDExterno){
            if(e.getNombre().equals(Panel_Deuda.externoactual.getNombre())){
               e.setDeuda(Panel_Deuda.externoactual.getDeuda());
            }
        }
        Flujos.Guardar(Principal.BDExterno, "Externo");
        Actualizar(Principal.BDExterno,"Externo");
        JFrame parentFrame = new JFrame();
        JOptionPane.showMessageDialog(parentFrame, "Se ha cancelado la deuda satisfactoriamente");
    }//GEN-LAST:event_jButton1ActionPerformed
    public  void obtenerDeuda(int deuda){
        String deudas = Integer.toString(deuda);
        tDeuda.setText("$"+deudas);
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tDeuda;
    // End of variables declaration//GEN-END:variables
}
