/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import Business.Principal;
import Data.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Panel_Pregunta extends javax.swing.JPanel {
    
    
    /**
     * Creates new form Panel_Estandar
     */
    public Panel_Pregunta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pregunta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        Confirmar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pregunta.setForeground(new java.awt.Color(0, 68, 51));
        pregunta.setBorder(null);
        pregunta.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        add(pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 109, 81));
        jLabel10.setText("Amigo de Infancia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 109, 81));
        jLabel1.setText("Has olvidado la contraseña. Contesta la pregunta");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 109, 81));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 10));

        jPanel1.setBackground(new java.awt.Color(0, 109, 81));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Confirmar.setBackground(new java.awt.Color(0, 109, 81));
        Confirmar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Confirmar.setForeground(new java.awt.Color(255, 255, 255));
        Confirmar.setText("Confirmar");
        Confirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Confirmar.setBorderPainted(false);
        Confirmar.setContentAreaFilled(false);
        Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarActionPerformed(evt);
            }
        });
        jPanel1.add(Confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, 20));
    }// </editor-fold>//GEN-END:initComponents
    
    private void ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarActionPerformed
        String p=pregunta.getText();
        System.out.println(Inicio.usuarioActual.getPregunta());
        Principal.recordarContraseña(Inicio.usuarioActual,p);
        
    }//GEN-LAST:event_ConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pregunta;
    // End of variables declaration//GEN-END:variables
}
