/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Data.*;
        
/**
 *
 * @author user
 */
public class Panel_Estudiante extends javax.swing.JPanel {

    public Estudiante es_guardar (){
        int i=es_tipo.getSelectedIndex();
        String t="";
        if(i==0){
            t="Pregrado";
        }if(i==1){
            t="Posgrado";
        }
        String Nombre = es_usuario.getText();
        String Contraseña = es_contraseña.getText();
        String Pregunta = es_pregunta.getText();
        String Cedula = es_cedula.getText();
        String Usuariosia=es_sia.getText();
        String Tipo=t;
        String Carrera=es_carrera.getText();
        String estado="Ninguno";
        Estudiante estudiante = new Estudiante(Nombre, Contraseña, estado, Cedula, Usuariosia, Tipo, Carrera,Pregunta);
        return estudiante;
    }
    
    public Panel_Estudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        es_carrera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        es_tipo = new javax.swing.JComboBox<>();
        es_usuario = new javax.swing.JTextField();
        es_pregunta = new javax.swing.JTextField();
        es_contraseña = new javax.swing.JTextField();
        es_cedula = new javax.swing.JTextField();
        es_sia = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 109, 81));
        jLabel10.setText("Amigo de Infancia");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 109, 81));
        jLabel11.setText("Usuario SIA");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 109, 81));
        jLabel3.setText("Usuario");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        es_carrera.setForeground(new java.awt.Color(0, 68, 51));
        es_carrera.setDisabledTextColor(new java.awt.Color(0, 109, 81));
        es_carrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                es_carreraActionPerformed(evt);
            }
        });
        add(es_carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 201, 140, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 109, 81));
        jLabel4.setText("Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 109, 81));
        jLabel6.setText("Carrera");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 201, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 109, 81));
        jLabel5.setText("Cédula Ciudadanía");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 109, 81));
        jLabel7.setText("Tipo");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        es_tipo.setForeground(new java.awt.Color(0, 68, 51));
        es_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pregrado", "Posgrado" }));
        es_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                es_tipoActionPerformed(evt);
            }
        });
        add(es_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 163, 140, -1));

        es_usuario.setForeground(new java.awt.Color(0, 68, 51));
        es_usuario.setDisabledTextColor(new java.awt.Color(0, 109, 81));
        es_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                es_usuarioActionPerformed(evt);
            }
        });
        add(es_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 11, 140, -1));

        es_pregunta.setForeground(new java.awt.Color(0, 68, 51));
        es_pregunta.setDisabledTextColor(new java.awt.Color(0, 109, 81));
        es_pregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                es_preguntaActionPerformed(evt);
            }
        });
        add(es_pregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 239, 140, -1));

        es_contraseña.setForeground(new java.awt.Color(0, 68, 51));
        es_contraseña.setDisabledTextColor(new java.awt.Color(0, 109, 81));
        add(es_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 49, 140, -1));

        es_cedula.setForeground(new java.awt.Color(0, 68, 51));
        es_cedula.setDisabledTextColor(new java.awt.Color(0, 109, 81));
        add(es_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 87, 140, -1));

        es_sia.setForeground(new java.awt.Color(0, 68, 51));
        es_sia.setDisabledTextColor(new java.awt.Color(0, 109, 81));
        es_sia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                es_siaActionPerformed(evt);
            }
        });
        add(es_sia, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 125, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void es_carreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_es_carreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_es_carreraActionPerformed

    private void es_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_es_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_es_tipoActionPerformed

    private void es_preguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_es_preguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_es_preguntaActionPerformed

    private void es_siaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_es_siaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_es_siaActionPerformed

    private void es_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_es_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_es_usuarioActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField es_carrera;
    private javax.swing.JTextField es_cedula;
    private javax.swing.JTextField es_contraseña;
    private javax.swing.JTextField es_pregunta;
    private javax.swing.JTextField es_sia;
    private javax.swing.JComboBox<String> es_tipo;
    private javax.swing.JTextField es_usuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
