/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Principal;
import Data.Estudiante;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Perfil_Estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Perfil
     */
    public Perfil_Estudiante() {
        
        initComponents();
        Estudiante estudianteactual=(Estudiante)Inicio.usuarioActual;
        esNombre.setText(estudianteactual.getNombre());   
        esContraseña.setText(estudianteactual.getContraseña());  
        esCedula.setText(estudianteactual.getCedula());  
        esUsuario.setText(estudianteactual.getUsuarioSia());  
        esTipo.setText(estudianteactual.getTipo());  
        esCarrera.setText(estudianteactual.getCarrera());  
        esEstado.setText(estudianteactual.getEstado()); 
        esPregunta.setText(estudianteactual.getPregunta()); 
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menú Inicio");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        esNombre = new javax.swing.JLabel();
        esContraseña = new javax.swing.JLabel();
        esCedula = new javax.swing.JLabel();
        esUsuario = new javax.swing.JLabel();
        esTipo = new javax.swing.JLabel();
        esCarrera = new javax.swing.JLabel();
        esEstado = new javax.swing.JLabel();
        esPregunta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 109, 81));
        jLabel10.setText("Pregunta");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 285, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 109, 81));
        jLabel11.setText("Usuario SIA");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 163, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 109, 81));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 71, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 109, 81));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 102, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 109, 81));
        jLabel6.setText("Carrera");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 223, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 109, 81));
        jLabel5.setText("Cédula Ciudadanía");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 132, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 109, 81));
        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 192, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 109, 81));
        jLabel1.setText("Estado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 254, -1, -1));

        esNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esNombre.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 71, -1, -1));

        esContraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esContraseña.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 103, -1, -1));

        esCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esCedula.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 132, -1, -1));

        esUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esUsuario.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 165, -1, -1));

        esTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esTipo.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 192, -1, -1));

        esCarrera.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esCarrera.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 223, -1, -1));

        esEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esEstado.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 254, -1, -1));

        esPregunta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        esPregunta.setForeground(new java.awt.Color(0, 109, 81));
        getContentPane().add(esPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 285, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 109, 81));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PERFIL");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 3, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 53));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 109, 81));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar Cuenta");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 140, 40));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 310, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame parentFrame = new JFrame();
        int answer = JOptionPane.showConfirmDialog(parentFrame,"¿Quieres borrar el contacto?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (answer==0){
           Principal.eliminarB(Inicio.usuarioActual,Inicio.usuarioActual.getRol());
           System.exit(0);
        }else{
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_Estudiante().setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel esCarrera;
    private javax.swing.JLabel esCedula;
    private javax.swing.JLabel esContraseña;
    private javax.swing.JLabel esEstado;
    private javax.swing.JLabel esNombre;
    private javax.swing.JLabel esPregunta;
    private javax.swing.JLabel esTipo;
    private javax.swing.JLabel esUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
