/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Business.Principal;

/**
 *
 * @author Jorge Hernández V
 */
public class Reservacion extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Reservacion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Menú Principal");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        torre_Emfermeria = new javax.swing.JRadioButton();
        biblioteca_Central = new javax.swing.JRadioButton();
        polideportivo = new javax.swing.JRadioButton();
        auditorio_Leon = new javax.swing.JRadioButton();
        derecho = new javax.swing.JRadioButton();
        aulas_Humanas = new javax.swing.JRadioButton();
        antonio_Narino = new javax.swing.JRadioButton();
        santander = new javax.swing.JRadioButton();
        geociencias = new javax.swing.JRadioButton();
        posgrados_Humanas = new javax.swing.JRadioButton();
        lenguas = new javax.swing.JRadioButton();
        enfermeria = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        musica = new javax.swing.JRadioButton();
        economicas = new javax.swing.JRadioButton();
        museo_Artes = new javax.swing.JRadioButton();
        viejo = new javax.swing.JRadioButton();
        FEM = new javax.swing.JRadioButton();
        IEI = new javax.swing.JRadioButton();
        posgrado_Materiales = new javax.swing.JRadioButton();
        CADE = new javax.swing.JRadioButton();
        lab_Hidraulica = new javax.swing.JRadioButton();
        lab_Ing_Quimica = new javax.swing.JRadioButton();
        observatorio = new javax.swing.JRadioButton();
        biologia = new javax.swing.JRadioButton();
        IPARM = new javax.swing.JRadioButton();
        quimica = new javax.swing.JRadioButton();
        aulas_Ingenieria = new javax.swing.JRadioButton();
        CyT = new javax.swing.JRadioButton();
        medicina = new javax.swing.JRadioButton();
        ciencias = new javax.swing.JRadioButton();
        veterinaria = new javax.swing.JRadioButton();
        agronomia = new javax.swing.JRadioButton();
        clinica_Animales = new javax.swing.JRadioButton();
        inseminacion = new javax.swing.JRadioButton();
        posgrados_Veterinaria = new javax.swing.JRadioButton();
        hemeroteca = new javax.swing.JRadioButton();
        porteria_Calle_45 = new javax.swing.JRadioButton();
        ingeominas = new javax.swing.JRadioButton();
        porteria_Transversal_38 = new javax.swing.JRadioButton();
        cine_y_Tv = new javax.swing.JRadioButton();
        estadio = new javax.swing.JRadioButton();
        concha_Acustica = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1235, 768));
        getContentPane().setLayout(null);

        buttonGroup1.add(torre_Emfermeria);
        torre_Emfermeria.setContentAreaFilled(false);
        torre_Emfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torre_EmfermeriaActionPerformed(evt);
            }
        });
        getContentPane().add(torre_Emfermeria);
        torre_Emfermeria.setBounds(880, 540, 21, 21);

        buttonGroup1.add(biblioteca_Central);
        biblioteca_Central.setContentAreaFilled(false);
        biblioteca_Central.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biblioteca_CentralActionPerformed(evt);
            }
        });
        getContentPane().add(biblioteca_Central);
        biblioteca_Central.setBounds(760, 520, 21, 21);

        buttonGroup1.add(polideportivo);
        polideportivo.setContentAreaFilled(false);
        polideportivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polideportivoActionPerformed(evt);
            }
        });
        getContentPane().add(polideportivo);
        polideportivo.setBounds(810, 600, 21, 21);

        auditorio_Leon.setBackground(new java.awt.Color(0, 51, 204));
        buttonGroup1.add(auditorio_Leon);
        auditorio_Leon.setForeground(new java.awt.Color(255, 153, 102));
        auditorio_Leon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        auditorio_Leon.setContentAreaFilled(false);
        auditorio_Leon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auditorio_LeonActionPerformed(evt);
            }
        });
        getContentPane().add(auditorio_Leon);
        auditorio_Leon.setBounds(850, 480, 23, 23);

        buttonGroup1.add(derecho);
        derecho.setContentAreaFilled(false);
        derecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechoActionPerformed(evt);
            }
        });
        getContentPane().add(derecho);
        derecho.setBounds(710, 520, 21, 21);

        buttonGroup1.add(aulas_Humanas);
        aulas_Humanas.setContentAreaFilled(false);
        aulas_Humanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aulas_HumanasActionPerformed(evt);
            }
        });
        getContentPane().add(aulas_Humanas);
        aulas_Humanas.setBounds(610, 640, 21, 21);

        buttonGroup1.add(antonio_Narino);
        antonio_Narino.setContentAreaFilled(false);
        antonio_Narino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antonio_NarinoActionPerformed(evt);
            }
        });
        getContentPane().add(antonio_Narino);
        antonio_Narino.setBounds(680, 700, 21, 21);

        buttonGroup1.add(santander);
        santander.setContentAreaFilled(false);
        santander.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                santanderActionPerformed(evt);
            }
        });
        getContentPane().add(santander);
        santander.setBounds(780, 710, 21, 21);

        buttonGroup1.add(geociencias);
        geociencias.setContentAreaFilled(false);
        geociencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geocienciasActionPerformed(evt);
            }
        });
        getContentPane().add(geociencias);
        geociencias.setBounds(520, 670, 21, 21);

        buttonGroup1.add(posgrados_Humanas);
        posgrados_Humanas.setContentAreaFilled(false);
        posgrados_Humanas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posgrados_HumanasActionPerformed(evt);
            }
        });
        getContentPane().add(posgrados_Humanas);
        posgrados_Humanas.setBounds(450, 640, 21, 21);

        buttonGroup1.add(lenguas);
        lenguas.setContentAreaFilled(false);
        lenguas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lenguasActionPerformed(evt);
            }
        });
        getContentPane().add(lenguas);
        lenguas.setBounds(690, 760, 21, 21);

        buttonGroup1.add(enfermeria);
        enfermeria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        enfermeria.setText("228");
        enfermeria.setContentAreaFilled(false);
        enfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermeriaActionPerformed(evt);
            }
        });
        getContentPane().add(enfermeria);
        enfermeria.setBounds(610, 530, 49, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Enfermería");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(620, 550, 62, 14);

        buttonGroup1.add(musica);
        musica.setContentAreaFilled(false);
        musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicaActionPerformed(evt);
            }
        });
        getContentPane().add(musica);
        musica.setBounds(930, 520, 21, 21);

        buttonGroup1.add(economicas);
        economicas.setContentAreaFilled(false);
        economicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economicasActionPerformed(evt);
            }
        });
        getContentPane().add(economicas);
        economicas.setBounds(970, 620, 21, 21);

        buttonGroup1.add(museo_Artes);
        museo_Artes.setContentAreaFilled(false);
        museo_Artes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                museo_ArtesActionPerformed(evt);
            }
        });
        getContentPane().add(museo_Artes);
        museo_Artes.setBounds(990, 390, 21, 21);

        buttonGroup1.add(viejo);
        viejo.setContentAreaFilled(false);
        viejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viejoActionPerformed(evt);
            }
        });
        getContentPane().add(viejo);
        viejo.setBounds(800, 360, 21, 21);

        buttonGroup1.add(FEM);
        FEM.setContentAreaFilled(false);
        FEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FEMActionPerformed(evt);
            }
        });
        getContentPane().add(FEM);
        FEM.setBounds(840, 310, 21, 21);

        buttonGroup1.add(IEI);
        IEI.setContentAreaFilled(false);
        IEI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IEIActionPerformed(evt);
            }
        });
        getContentPane().add(IEI);
        IEI.setBounds(810, 240, 21, 21);

        buttonGroup1.add(posgrado_Materiales);
        posgrado_Materiales.setContentAreaFilled(false);
        posgrado_Materiales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posgrado_MaterialesActionPerformed(evt);
            }
        });
        getContentPane().add(posgrado_Materiales);
        posgrado_Materiales.setBounds(850, 180, 21, 21);

        buttonGroup1.add(CADE);
        CADE.setContentAreaFilled(false);
        CADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADEActionPerformed(evt);
            }
        });
        getContentPane().add(CADE);
        CADE.setBounds(920, 260, 21, 21);

        buttonGroup1.add(lab_Hidraulica);
        lab_Hidraulica.setContentAreaFilled(false);
        lab_Hidraulica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_HidraulicaActionPerformed(evt);
            }
        });
        getContentPane().add(lab_Hidraulica);
        lab_Hidraulica.setBounds(890, 200, 21, 21);

        buttonGroup1.add(lab_Ing_Quimica);
        lab_Ing_Quimica.setContentAreaFilled(false);
        lab_Ing_Quimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lab_Ing_QuimicaActionPerformed(evt);
            }
        });
        getContentPane().add(lab_Ing_Quimica);
        lab_Ing_Quimica.setBounds(760, 200, 21, 21);

        buttonGroup1.add(observatorio);
        observatorio.setContentAreaFilled(false);
        observatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observatorioActionPerformed(evt);
            }
        });
        getContentPane().add(observatorio);
        observatorio.setBounds(740, 130, 21, 21);

        buttonGroup1.add(biologia);
        biologia.setContentAreaFilled(false);
        biologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologiaActionPerformed(evt);
            }
        });
        getContentPane().add(biologia);
        biologia.setBounds(860, 10, 21, 21);

        buttonGroup1.add(IPARM);
        IPARM.setContentAreaFilled(false);
        IPARM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IPARMActionPerformed(evt);
            }
        });
        getContentPane().add(IPARM);
        IPARM.setBounds(720, 20, 21, 21);

        buttonGroup1.add(quimica);
        quimica.setContentAreaFilled(false);
        quimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quimicaActionPerformed(evt);
            }
        });
        getContentPane().add(quimica);
        quimica.setBounds(670, 330, 21, 21);

        buttonGroup1.add(aulas_Ingenieria);
        aulas_Ingenieria.setContentAreaFilled(false);
        aulas_Ingenieria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aulas_IngenieriaActionPerformed(evt);
            }
        });
        getContentPane().add(aulas_Ingenieria);
        aulas_Ingenieria.setBounds(740, 220, 21, 21);

        buttonGroup1.add(CyT);
        CyT.setContentAreaFilled(false);
        CyT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CyTActionPerformed(evt);
            }
        });
        getContentPane().add(CyT);
        CyT.setBounds(610, 280, 21, 21);

        buttonGroup1.add(medicina);
        medicina.setContentAreaFilled(false);
        medicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinaActionPerformed(evt);
            }
        });
        getContentPane().add(medicina);
        medicina.setBounds(640, 430, 21, 21);

        buttonGroup1.add(ciencias);
        ciencias.setContentAreaFilled(false);
        ciencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cienciasActionPerformed(evt);
            }
        });
        getContentPane().add(ciencias);
        ciencias.setBounds(570, 330, 21, 21);

        buttonGroup1.add(veterinaria);
        veterinaria.setContentAreaFilled(false);
        veterinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veterinariaActionPerformed(evt);
            }
        });
        getContentPane().add(veterinaria);
        veterinaria.setBounds(580, 440, 21, 21);

        buttonGroup1.add(agronomia);
        agronomia.setContentAreaFilled(false);
        agronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agronomiaActionPerformed(evt);
            }
        });
        getContentPane().add(agronomia);
        agronomia.setBounds(390, 440, 21, 21);

        buttonGroup1.add(clinica_Animales);
        clinica_Animales.setContentAreaFilled(false);
        clinica_Animales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinica_AnimalesActionPerformed(evt);
            }
        });
        getContentPane().add(clinica_Animales);
        clinica_Animales.setBounds(520, 450, 21, 21);

        buttonGroup1.add(inseminacion);
        inseminacion.setContentAreaFilled(false);
        inseminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inseminacionActionPerformed(evt);
            }
        });
        getContentPane().add(inseminacion);
        inseminacion.setBounds(530, 490, 21, 21);

        buttonGroup1.add(posgrados_Veterinaria);
        posgrados_Veterinaria.setContentAreaFilled(false);
        posgrados_Veterinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posgrados_VeterinariaActionPerformed(evt);
            }
        });
        getContentPane().add(posgrados_Veterinaria);
        posgrados_Veterinaria.setBounds(410, 330, 21, 21);

        buttonGroup1.add(hemeroteca);
        hemeroteca.setContentAreaFilled(false);
        hemeroteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hemerotecaActionPerformed(evt);
            }
        });
        getContentPane().add(hemeroteca);
        hemeroteca.setBounds(30, 390, 21, 21);

        buttonGroup1.add(porteria_Calle_45);
        porteria_Calle_45.setContentAreaFilled(false);
        porteria_Calle_45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porteria_Calle_45ActionPerformed(evt);
            }
        });
        getContentPane().add(porteria_Calle_45);
        porteria_Calle_45.setBounds(1020, 560, 21, 21);

        buttonGroup1.add(ingeominas);
        ingeominas.setContentAreaFilled(false);
        ingeominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingeominasActionPerformed(evt);
            }
        });
        getContentPane().add(ingeominas);
        ingeominas.setBounds(960, 150, 21, 21);

        buttonGroup1.add(porteria_Transversal_38);
        porteria_Transversal_38.setContentAreaFilled(false);
        porteria_Transversal_38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porteria_Transversal_38ActionPerformed(evt);
            }
        });
        getContentPane().add(porteria_Transversal_38);
        porteria_Transversal_38.setBounds(270, 160, 21, 21);

        buttonGroup1.add(cine_y_Tv);
        cine_y_Tv.setContentAreaFilled(false);
        cine_y_Tv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cine_y_TvActionPerformed(evt);
            }
        });
        getContentPane().add(cine_y_Tv);
        cine_y_Tv.setBounds(540, 50, 21, 21);

        buttonGroup1.add(estadio);
        estadio.setContentAreaFilled(false);
        estadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadioActionPerformed(evt);
            }
        });
        getContentPane().add(estadio);
        estadio.setBounds(460, 50, 21, 21);

        buttonGroup1.add(concha_Acustica);
        concha_Acustica.setContentAreaFilled(false);
        concha_Acustica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concha_AcusticaActionPerformed(evt);
            }
        });
        getContentPane().add(concha_Acustica);
        concha_Acustica.setBounds(390, 180, 21, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/mapa_copia_3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -110, 1230, 1000);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void torre_EmfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torre_EmfermeriaActionPerformed
       Principal.buscarParqueadero("101");
       Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_torre_EmfermeriaActionPerformed

    private void enfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermeriaActionPerformed
       Principal.buscarParqueadero("228");
       Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_enfermeriaActionPerformed

    private void biblioteca_CentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biblioteca_CentralActionPerformed
        Principal.buscarParqueadero("102");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_biblioteca_CentralActionPerformed

    private void polideportivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polideportivoActionPerformed
        Principal.buscarParqueadero("103");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_polideportivoActionPerformed

    private void auditorio_LeonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auditorio_LeonActionPerformed
        Principal.buscarParqueadero("104");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_auditorio_LeonActionPerformed

    private void derechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechoActionPerformed
       Principal.buscarParqueadero("201");
       Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_derechoActionPerformed

    private void aulas_HumanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aulas_HumanasActionPerformed
        Principal.buscarParqueadero("212");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_aulas_HumanasActionPerformed

    private void antonio_NarinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antonio_NarinoActionPerformed
        Principal.buscarParqueadero("214");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_antonio_NarinoActionPerformed

    private void santanderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_santanderActionPerformed
        Principal.buscarParqueadero("217");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_santanderActionPerformed

    private void geocienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geocienciasActionPerformed
        Principal.buscarParqueadero("224");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_geocienciasActionPerformed

    private void posgrados_HumanasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posgrados_HumanasActionPerformed
        Principal.buscarParqueadero("225");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_posgrados_HumanasActionPerformed

    private void lenguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lenguasActionPerformed
        Principal.buscarParqueadero("231");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_lenguasActionPerformed

    private void hemerotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hemerotecaActionPerformed
        Principal.buscarParqueadero("571");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_hemerotecaActionPerformed

    private void musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicaActionPerformed
        Principal.buscarParqueadero("305");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_musicaActionPerformed

    private void economicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economicasActionPerformed
        Principal.buscarParqueadero("311");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_economicasActionPerformed

    private void museo_ArtesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_museo_ArtesActionPerformed
        Principal.buscarParqueadero("317");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_museo_ArtesActionPerformed

    private void viejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viejoActionPerformed
        Principal.buscarParqueadero("401");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_viejoActionPerformed

    private void FEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FEMActionPerformed
        Principal.buscarParqueadero("404");Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true);               
    }//GEN-LAST:event_FEMActionPerformed

    private void IEIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IEIActionPerformed
        Principal.buscarParqueadero("406");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_IEIActionPerformed

    private void posgrado_MaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posgrado_MaterialesActionPerformed
        Principal.buscarParqueadero("407");Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_posgrado_MaterialesActionPerformed

    private void CADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADEActionPerformed
        Principal.buscarParqueadero("408");Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_CADEActionPerformed

    private void lab_HidraulicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_HidraulicaActionPerformed
        Principal.buscarParqueadero("409");Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_lab_HidraulicaActionPerformed

    private void lab_Ing_QuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lab_Ing_QuimicaActionPerformed
        Principal.buscarParqueadero("412");Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_lab_Ing_QuimicaActionPerformed

    private void observatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observatorioActionPerformed
        Principal.buscarParqueadero("413");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_observatorioActionPerformed

    private void biologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologiaActionPerformed
        Principal.buscarParqueadero("421");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_biologiaActionPerformed

    private void IPARMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IPARMActionPerformed
        Principal.buscarParqueadero("431");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_IPARMActionPerformed

    private void quimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quimicaActionPerformed
        Principal.buscarParqueadero("451");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_quimicaActionPerformed

    private void aulas_IngenieriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aulas_IngenieriaActionPerformed
        Principal.buscarParqueadero("453");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_aulas_IngenieriaActionPerformed

    private void CyTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CyTActionPerformed
        Principal.buscarParqueadero("454");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_CyTActionPerformed

    private void medicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinaActionPerformed
        Principal.buscarParqueadero("471");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_medicinaActionPerformed

    private void cienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cienciasActionPerformed
        Principal.buscarParqueadero("476");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_cienciasActionPerformed

    private void veterinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veterinariaActionPerformed
        Principal.buscarParqueadero("481");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_veterinariaActionPerformed

    private void agronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agronomiaActionPerformed
        Principal.buscarParqueadero("500");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_agronomiaActionPerformed

    private void clinica_AnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinica_AnimalesActionPerformed
        Principal.buscarParqueadero("501");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_clinica_AnimalesActionPerformed

    private void inseminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inseminacionActionPerformed
        Principal.buscarParqueadero("502");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_inseminacionActionPerformed

    private void posgrados_VeterinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posgrados_VeterinariaActionPerformed
        Principal.buscarParqueadero("561");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_posgrados_VeterinariaActionPerformed

    private void porteria_Calle_45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porteria_Calle_45ActionPerformed
        Principal.buscarParqueadero("603");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_porteria_Calle_45ActionPerformed

    private void ingeominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingeominasActionPerformed
        Principal.buscarParqueadero("615");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_ingeominasActionPerformed

    private void porteria_Transversal_38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porteria_Transversal_38ActionPerformed
        Principal.buscarParqueadero("700");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_porteria_Transversal_38ActionPerformed

    private void cine_y_TvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cine_y_TvActionPerformed
        Principal.buscarParqueadero("701");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_cine_y_TvActionPerformed

    private void estadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadioActionPerformed
        Principal.buscarParqueadero("731");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_estadioActionPerformed

    private void concha_AcusticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concha_AcusticaActionPerformed
        Principal.buscarParqueadero("761");
        Panel_Parqueadero parqueadero= new Panel_Parqueadero();
                parqueadero.setVisible(true); 
    }//GEN-LAST:event_concha_AcusticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CADE;
    private javax.swing.JRadioButton CyT;
    private javax.swing.JRadioButton FEM;
    private javax.swing.JRadioButton IEI;
    private javax.swing.JRadioButton IPARM;
    private javax.swing.JRadioButton agronomia;
    private javax.swing.JRadioButton antonio_Narino;
    private javax.swing.JRadioButton auditorio_Leon;
    private javax.swing.JRadioButton aulas_Humanas;
    private javax.swing.JRadioButton aulas_Ingenieria;
    private javax.swing.JRadioButton biblioteca_Central;
    private javax.swing.JRadioButton biologia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton ciencias;
    private javax.swing.JRadioButton cine_y_Tv;
    private javax.swing.JRadioButton clinica_Animales;
    private javax.swing.JRadioButton concha_Acustica;
    private javax.swing.JRadioButton derecho;
    private javax.swing.JRadioButton economicas;
    private javax.swing.JRadioButton enfermeria;
    private javax.swing.JRadioButton estadio;
    private javax.swing.JRadioButton geociencias;
    private javax.swing.JRadioButton hemeroteca;
    private javax.swing.JRadioButton ingeominas;
    private javax.swing.JRadioButton inseminacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton lab_Hidraulica;
    private javax.swing.JRadioButton lab_Ing_Quimica;
    private javax.swing.JRadioButton lenguas;
    private javax.swing.JRadioButton medicina;
    private javax.swing.JRadioButton museo_Artes;
    private javax.swing.JRadioButton musica;
    private javax.swing.JRadioButton observatorio;
    private javax.swing.JRadioButton polideportivo;
    private javax.swing.JRadioButton porteria_Calle_45;
    private javax.swing.JRadioButton porteria_Transversal_38;
    private javax.swing.JRadioButton posgrado_Materiales;
    private javax.swing.JRadioButton posgrados_Humanas;
    private javax.swing.JRadioButton posgrados_Veterinaria;
    private javax.swing.JRadioButton quimica;
    private javax.swing.JRadioButton santander;
    private javax.swing.JRadioButton torre_Emfermeria;
    private javax.swing.JRadioButton veterinaria;
    private javax.swing.JRadioButton viejo;
    // End of variables declaration//GEN-END:variables
}
